name: utils
description: "A collection of utility functions"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  android_intent_plus: ^5.3.0
  biometric_signature: ^6.2.0
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.3.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.1
  package_info_plus: ^8.2.1
  path_provider: ^2.1.5
  rusty_dart:
    git:
      url: https://github.com/TheMakersPrime/rusty_dart.git
      ref: main
  shared_preferences: ^2.5.3
  sherlog:
    git:
      url: https://github.com/TheMakersPrime/sherlog.git
      ref: main
  stack_trace: ^1.12.0
  url_launcher: ^6.2.5
  uuid: ^4.5.1

dev_dependencies:
  very_good_analysis: ^7.0.0